[package]
name = "qcderive-test"
version = "0.1.0"
edition = "2021"
publish = false
license = "MPL-2.0"
build = "build.rs"

[dependencies]
breadth-first-zip = { path = "../../breadth-first-zip" }
derive-quickcheck = { path = ".." }
quickcheck = ">=1"
